/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/diff/baseline": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Compare a URL against a stored baseline
         * @description Resolves the baseline for {project, page_name, branch} (falling back to the project default branch when an exact match is missing) and runs a visual diff against the supplied `after` URL. Use this when you have a SnapDiff project set up and want to verify a page still matches its approved state — equivalent to /diff but with baseline lookup done server-side in one round trip.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /**
                         * @description URL, image URL, or screenshot ID (ss_xxx) for the "after" state to compare against the stored baseline
                         * @example https://staging.example.com/pricing
                         */
                        after: string;
                        /**
                         * @description Project slug or ID (prj_xxx)
                         * @example acme-marketing
                         */
                        project: string;
                        /**
                         * @description Page name within the project
                         * @example pricing
                         */
                        page_name: string;
                        /**
                         * @description Branch to look up the baseline on. Falls back to the project default branch and then to the project default branch baseline.
                         * @example main
                         */
                        branch?: string;
                        /**
                         * @description Pixel sensitivity 0.0-1.0
                         * @example 0.1
                         */
                        threshold?: number;
                        /**
                         * @description Hex color for diff highlights
                         * @example #ff0000
                         */
                        diff_color?: string;
                        /** @description Rectangular regions to exclude from comparison */
                        ignore_regions?: {
                            x: number;
                            y: number;
                            width: number;
                            height: number;
                        }[];
                        /**
                         * @description CSS selectors to mask before comparison
                         * @example [
                         *       ".dynamic-date",
                         *       "#ad-banner"
                         *     ]
                         */
                        ignore_selectors?: string[];
                        /** @description Ignore sub-pixel rendering differences */
                        antialiasing?: boolean;
                        /** @description Options applied when capturing the after screenshot */
                        screenshot_options?: {
                            viewport?: {
                                width?: number;
                                height?: number;
                            };
                            full_page?: boolean;
                            block?: {
                                ads?: boolean;
                                cookie_banners?: boolean;
                            };
                        };
                    };
                };
            };
            responses: {
                /** @description Diff result, including the baseline that was resolved */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example df_xyz789 */
                            id: string;
                            match: boolean;
                            /** @example 3.42 */
                            diff_percentage: number;
                            diff_pixel_count: number;
                            total_pixels: number;
                            /** Format: uri */
                            diff_image_url: string;
                            /** Format: uri */
                            before_image_url: string;
                            /** Format: uri */
                            after_image_url: string;
                            /** Format: uri */
                            overlay_image_url: string;
                            changed_regions: {
                                x: number;
                                y: number;
                                width: number;
                                height: number;
                                label: string;
                            }[];
                            dimensions: {
                                width: number;
                                height: number;
                            };
                            duration_ms: number;
                            baseline: {
                                project_id: string;
                                project_slug: string;
                                page_name: string;
                                branch: string;
                                baseline_id: string;
                            };
                        };
                    };
                };
                /** @description Missing or invalid API key */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Diff quota exceeded */
                402: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Project or baseline not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: {
                                message: string;
                                code?: string;
                            };
                        };
                    };
                };
                /** @description Rate limit exceeded */
                429: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/diff": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Compare two URLs visually
         * @description The core product endpoint. Send two URLs (or screenshot IDs), get back a diff percentage and highlighted diff image showing exactly what changed.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /**
                         * @description URL, image URL, or screenshot ID (ss_xxx) for the "before" state
                         * @example https://example.com
                         */
                        before: string;
                        /**
                         * @description URL, image URL, or screenshot ID (ss_xxx) for the "after" state
                         * @example https://staging.example.com
                         */
                        after: string;
                        /**
                         * @description Pixel sensitivity 0.0-1.0
                         * @example 0.1
                         */
                        threshold?: number;
                        /**
                         * @description Hex color for diff highlights
                         * @example #ff0000
                         */
                        diff_color?: string;
                        /** @description Rectangular regions to exclude from comparison */
                        ignore_regions?: {
                            x: number;
                            y: number;
                            width: number;
                            height: number;
                        }[];
                        /**
                         * @description CSS selectors to mask before comparison
                         * @example [
                         *       ".dynamic-date",
                         *       "#ad-banner"
                         *     ]
                         */
                        ignore_selectors?: string[];
                        /**
                         * @description Ignore sub-pixel rendering differences
                         * @example true
                         */
                        antialiasing?: boolean;
                        /** @description Options applied when capturing before/after screenshots */
                        screenshot_options?: {
                            viewport?: {
                                width?: number;
                                height?: number;
                            };
                            full_page?: boolean;
                            block?: {
                                ads?: boolean;
                                cookie_banners?: boolean;
                            };
                        };
                    };
                };
            };
            responses: {
                /** @description Diff result with images and changed regions */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example df_xyz789 */
                            id: string;
                            match: boolean;
                            /** @example 3.42 */
                            diff_percentage: number;
                            diff_pixel_count: number;
                            total_pixels: number;
                            /** Format: uri */
                            diff_image_url: string;
                            /** Format: uri */
                            before_image_url: string;
                            /** Format: uri */
                            after_image_url: string;
                            /** Format: uri */
                            overlay_image_url: string;
                            changed_regions: {
                                x: number;
                                y: number;
                                width: number;
                                height: number;
                                label: string;
                            }[];
                            dimensions: {
                                width: number;
                                height: number;
                            };
                            duration_ms: number;
                        };
                    };
                };
                /** @description Missing or invalid API key */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Diff quota exceeded */
                402: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Rate limit exceeded */
                429: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/screenshot": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Take a screenshot
         * @description Capture a screenshot of a URL or render HTML to an image. Supporting infrastructure for the diff endpoint.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /**
                         * Format: uri
                         * @description URL to screenshot (required unless html is provided)
                         * @example https://example.com
                         */
                        url?: string;
                        /** @description Raw HTML to render (alternative to url) */
                        html?: string;
                        /**
                         * @description Viewport width
                         * @example 1280
                         */
                        width?: number;
                        /**
                         * @description Viewport height
                         * @example 720
                         */
                        height?: number;
                        /**
                         * @description Output image format
                         * @example webp
                         * @enum {string}
                         */
                        format?: "png" | "jpeg" | "webp";
                        /**
                         * @description Image quality (ignored for png)
                         * @example 80
                         */
                        quality?: number;
                        /**
                         * @description Device scale factor (retina)
                         * @example 2
                         */
                        scale?: number;
                        /** @description Capture full scrollable page */
                        full_page?: boolean;
                        /** @description Force dark color scheme */
                        dark_mode?: boolean;
                        /** @description CSS selector to capture only this element */
                        selector?: string;
                        /**
                         * @description Block ads, cookie banners, and chat widgets
                         * @example true
                         */
                        block_ads?: boolean;
                        /** @description Extra delay after page load in ms */
                        delay_ms?: number;
                        /**
                         * @description Cache duration in seconds (0 = skip cache)
                         * @example 86400
                         */
                        cache_ttl?: number;
                    };
                };
            };
            responses: {
                /** @description Screenshot captured successfully */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example ss_abc123 */
                            id: string;
                            /**
                             * Format: uri
                             * @description CDN URL of the screenshot
                             */
                            url: string;
                            width: number;
                            height: number;
                            /** @description File size in bytes */
                            file_size: number;
                            duration_ms: number;
                            cached: boolean;
                        };
                    };
                };
                /** @description Missing or invalid API key */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Screenshot quota exceeded */
                402: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Rate limit exceeded */
                429: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List projects
         * @description List all projects belonging to the authenticated user.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Array of projects */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example prj_abc123 */
                            id: string;
                            /** @example Marketing Site */
                            name: string;
                            /** @example marketing-site */
                            slug: string;
                            /** @example main */
                            default_branch: string;
                            created_at: string | null;
                            updated_at: string | null;
                        }[];
                    };
                };
            };
        };
        put?: never;
        /**
         * Create a project
         * @description Create a new project to organize baselines and builds. Projects group visual regression tests for a single site or app.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /**
                         * @description Human-readable project name
                         * @example Marketing Site
                         */
                        name: string;
                        /**
                         * @description URL-safe identifier (lowercase, hyphens allowed)
                         * @example marketing-site
                         */
                        slug: string;
                        /**
                         * @description Default branch for baseline resolution (defaults to "main")
                         * @example main
                         */
                        default_branch?: string;
                    };
                };
            };
            responses: {
                /** @description Project created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example prj_abc123 */
                            id: string;
                            /** @example Marketing Site */
                            name: string;
                            /** @example marketing-site */
                            slug: string;
                            /** @example main */
                            default_branch: string;
                            created_at: string | null;
                            updated_at: string | null;
                        };
                    };
                };
                /** @description Project limit reached on current plan */
                402: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Project with this slug already exists */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{projectId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get project details
         * @description Get a project with baseline and build counts.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    projectId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Project details */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example prj_abc123 */
                            id: string;
                            /** @example Marketing Site */
                            name: string;
                            /** @example marketing-site */
                            slug: string;
                            /** @example main */
                            default_branch: string;
                            created_at: string | null;
                            updated_at: string | null;
                            /** @example 5 */
                            baseline_count: number;
                            /** @example 12 */
                            build_count: number;
                        };
                    };
                };
                /** @description Project not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        /**
         * Delete a project
         * @description Delete a project and all its baselines, builds, and snapshots (cascade).
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    projectId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Project deleted */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            deleted: boolean;
                            id: string;
                        };
                    };
                };
                /** @description Project not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        /** Update a project */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    projectId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @example Updated Name */
                        name?: string;
                        slug?: string;
                        default_branch?: string;
                    };
                };
            };
            responses: {
                /** @description Project updated */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            updated: boolean;
                            id: string;
                        };
                    };
                };
                /** @description Project not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Slug conflict */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        trace?: never;
    };
    "/projects/{projectId}/github": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get GitHub integration config */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    projectId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description GitHub config */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            project_id: string;
                            repo: string;
                            status_enabled: boolean;
                            /**
                             * @description Last 4 characters of the token (for display)
                             * @example •••• xxxx
                             */
                            token_last4: string;
                            created_at: string | null;
                        };
                    };
                };
                /** @description Project not found or GitHub not configured */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        /**
         * Configure GitHub integration
         * @description Set up GitHub commit status reporting for a project. Provide a PAT with `repo:status` scope and the repo name. SnapDiff will post commit statuses when builds complete.
         */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    projectId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /**
                         * @description GitHub repo in "owner/name" format
                         * @example acme-corp/marketing-site
                         */
                        repo: string;
                        /**
                         * @description GitHub personal access token with repo:status scope
                         * @example ghp_xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
                         */
                        token: string;
                        /**
                         * @description Whether to post commit statuses (default true)
                         * @example true
                         */
                        status_enabled?: boolean;
                    };
                };
            };
            responses: {
                /** @description GitHub config saved */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            project_id: string;
                            repo: string;
                            status_enabled: boolean;
                            /**
                             * @description Last 4 characters of the token (for display)
                             * @example •••• xxxx
                             */
                            token_last4: string;
                            created_at: string | null;
                        };
                    };
                };
                /** @description Project not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        post?: never;
        /**
         * Remove GitHub integration
         * @description Remove GitHub config from a project. Commit statuses will no longer be posted.
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    projectId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Config removed */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            deleted: boolean;
                        };
                    };
                };
                /** @description Project not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{projectId}/builds": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List builds
         * @description List builds for a project, optionally filtered by branch or status.
         */
        get: {
            parameters: {
                query?: {
                    branch?: string;
                    status?: "pending" | "processing" | "approved" | "changes_requested" | "failed";
                    limit?: string;
                    offset?: string;
                };
                header?: never;
                path: {
                    projectId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Array of builds */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example bld_xyz789 */
                            id: string;
                            project_id: string;
                            /** @example feature/new-header */
                            branch: string | null;
                            /** @example abc123def */
                            commit_sha: string | null;
                            commit_message: string | null;
                            pull_request_url: string | null;
                            /**
                             * @example changes_requested
                             * @enum {string}
                             */
                            status: "pending" | "processing" | "approved" | "changes_requested" | "failed";
                            /** @example 5 */
                            total_snapshots: number;
                            /** @example 2 */
                            changed_count: number;
                            /** @example 3 */
                            approved_count: number;
                            created_at: string | null;
                        }[];
                    };
                };
                /** @description Project not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        /**
         * Create a build
         * @description Start a visual regression test. Screenshots each page, diffs against baselines, and returns results. Processing is async — poll the build detail endpoint for results.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    projectId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /**
                         * @description Branch name (defaults to project default_branch)
                         * @example feature/new-header
                         */
                        branch?: string;
                        /**
                         * @description Git commit SHA
                         * @example abc123def456
                         */
                        commit_sha?: string;
                        /**
                         * @description Git commit message
                         * @example Update hero section
                         */
                        commit_message?: string;
                        /**
                         * Format: uri
                         * @description GitHub/GitLab PR URL
                         * @example https://github.com/org/repo/pull/42
                         */
                        pull_request_url?: string;
                        /**
                         * @description Extra HTTP headers applied to every request during page capture. Used to authenticate against protected previews (Vercel deployment protection, Cloudflare Access, basic auth, etc). Header values are not persisted to the database.
                         * @example {
                         *       "x-vercel-protection-bypass": "secret-value",
                         *       "x-vercel-set-bypass-cookie": "true"
                         *     }
                         */
                        headers?: {
                            [key: string]: string;
                        };
                        /** @description Pages to compare against baselines. Each page either references a URL (worker will capture) or a pre-uploaded screenshot id. */
                        pages: {
                            /**
                             * @description Page identifier (used for baseline matching)
                             * @example homepage
                             */
                            name: string;
                            /**
                             * Format: uri
                             * @description URL to screenshot (worker captures it). Mutually exclusive with screenshot_id.
                             * @example https://staging.myapp.com/
                             */
                            url?: string;
                            /**
                             * @description Pre-captured screenshot id from POST /v1/screenshot/upload. Use when the customer is providing PNGs (e.g. via the Playwright reporter). Mutually exclusive with url.
                             * @example ss_abc123
                             */
                            screenshot_id?: string;
                        }[];
                    };
                };
            };
            responses: {
                /** @description Build accepted for processing */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            id: string;
                            project_id: string;
                            /** @example processing */
                            status: string;
                            total_snapshots: number;
                            branch: string;
                            /** @example /v1/projects/prj_abc/builds/bld_xyz */
                            poll_url: string;
                        };
                    };
                };
                /** @description Build quota exceeded */
                402: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Project not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{projectId}/builds/{buildId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get build details
         * @description Get a build with all its snapshots, diff images, and review status. Use this to poll for build completion and review results.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    projectId: string;
                    buildId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Build with snapshots */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example bld_xyz789 */
                            id: string;
                            project_id: string;
                            /** @example feature/new-header */
                            branch: string | null;
                            /** @example abc123def */
                            commit_sha: string | null;
                            commit_message: string | null;
                            pull_request_url: string | null;
                            /**
                             * @example changes_requested
                             * @enum {string}
                             */
                            status: "pending" | "processing" | "approved" | "changes_requested" | "failed";
                            /** @example 5 */
                            total_snapshots: number;
                            /** @example 2 */
                            changed_count: number;
                            /** @example 3 */
                            approved_count: number;
                            created_at: string | null;
                            snapshots: {
                                /** @example bsn_abc123 */
                                id: string;
                                /** @example homepage */
                                page_name: string;
                                /** @example https://staging.myapp.com/ */
                                url: string;
                                baseline_id: string | null;
                                screenshot_id: string | null;
                                /** @example https://cdn.snapdiff.dev/v1/ss_abc.png */
                                screenshot_url: string | null;
                                diff_id: string | null;
                                diff_image_url: string | null;
                                overlay_image_url: string | null;
                                /** @example 2.1 */
                                diff_percentage: number | null;
                                /**
                                 * @example pending
                                 * @enum {string}
                                 */
                                status: "pending" | "approved" | "rejected" | "unchanged" | "new";
                                reviewed_by: string | null;
                                reviewed_at: string | null;
                            }[];
                        };
                    };
                };
                /** @description Build or project not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{projectId}/builds/{buildId}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Approve entire build
         * @description Approve all pending snapshots in a build. Updates baselines with the new screenshots. This is the batch approval endpoint.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    projectId: string;
                    buildId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Build approved */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            approved: boolean;
                            build_id: string;
                            baselines_updated: number;
                        };
                    };
                };
                /** @description Build or project not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{projectId}/builds/{buildId}/snapshots/{snapshotId}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Approve a single snapshot
         * @description Approve one snapshot and update its baseline. Automatically recalculates the build status.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    projectId: string;
                    buildId: string;
                    snapshotId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Snapshot approved */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            approved: boolean;
                            snapshot_id: string;
                            baseline_updated: boolean;
                        };
                    };
                };
                /** @description Snapshot, build, or project not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{projectId}/builds/{buildId}/snapshots/{snapshotId}/reject": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Reject a single snapshot
         * @description Reject a visual change. The baseline is NOT updated. Automatically recalculates the build status.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    projectId: string;
                    buildId: string;
                    snapshotId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Snapshot rejected */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            rejected: boolean;
                            snapshot_id: string;
                        };
                    };
                };
                /** @description Snapshot, build, or project not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{projectId}/baselines": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List baselines
         * @description List all current baselines for a project. Each baseline represents the last accepted screenshot for a page on a branch.
         */
        get: {
            parameters: {
                query?: {
                    branch?: string;
                };
                header?: never;
                path: {
                    projectId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Array of baselines */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example bl_abc123 */
                            id: string;
                            /** @example homepage */
                            page_name: string;
                            /** @example main */
                            branch: string;
                            screenshot_id: string;
                            /** @example https://cdn.snapdiff.dev/v1/ss_abc.png */
                            screenshot_url: string;
                            accepted_by: string | null;
                            accepted_at: string | null;
                            created_at: string | null;
                        }[];
                    };
                };
                /** @description Project not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{projectId}/baselines/{baselineId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete a baseline
         * @description Delete a baseline. The next build will treat this page as new (no comparison). The underlying screenshot is not deleted.
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    projectId: string;
                    baselineId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Baseline deleted */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            deleted: boolean;
                            id: string;
                        };
                    };
                };
                /** @description Baseline or project not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: never;
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
